### ISSUE TITLE
As an author, When I befriend someone (they accept my friend request) I follow them, only when the other author befriends me do I count as a real friend – a bi-directional follow is a true friend.

### ISSUE THREAD

**Issue by em1i** [CMPUT404-Social-Distribution-Project/mondaylab-cmput404-project#35]

**Comment by nervuna** [comment]
What is the difference between a real friend and a true friend (no this is not a question about real life friends)? If a real friend = when other author befriends me, this would imply that the relationship is bidirectional, so why differentiate between the two? Or perhaps real friend = other author befriends me, but I haven't befriended them; this would be the same concept as having followers.

**Comment by jackie174** [comment]
What I understand, they are followed each others, (Like A follow B, B follow A), Then they are friends, no matter whether True or Real
Otherwise, they just follower - relationship
